### - Whatever this is (It's needed in order for the rest api to work)

### Get todos list
GET http://localhost:3000/todos/

### Register request
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "myusername",
    "password": "123"
}

### Log in request
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "myusername",
    "password": "123"
}

### Fetch all todos (protected<?>)
GET http://localhost:3000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzUxODk2Njk1LCJleHAiOjE3NTE4OTcyOTV9.5kg9tjiRKxsrJp87cccn0aBsT6QE5DYI48xdd8yhMqE

### Create a new todo (protected<?>)
POST http://localhost:3000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzUxODk2Njk1LCJleHAiOjE3NTE4OTcyOTV9.5kg9tjiRKxsrJp87cccn0aBsT6QE5DYI48xdd8yhMqE
Content-Type: application/json

{
    "task": "Finish coding"
}

### Change the status of a todo
PUT http://localhost:3000/todos/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzUxODk2Njk1LCJleHAiOjE3NTE4OTcyOTV9.5kg9tjiRKxsrJp87cccn0aBsT6QE5DYI48xdd8yhMqE
Content-Type: application/json

{
    "status": 1
}

### Delete a todo
DELETE http://localhost:3000/todos/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzUxODk2Njk1LCJleHAiOjE3NTE4OTcyOTV9.5kg9tjiRKxsrJp87cccn0aBsT6QE5DYI48xdd8yhMqE

